// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgmtlo_KK_4uIyAS1TUZ4sBj9UEXScIUY',
    appId: '1:276215361319:web:c49f2dafc6a6e4f2900302',
    messagingSenderId: '276215361319',
    projectId: 'ngwordgame',
    authDomain: 'ngwordgame.firebaseapp.com',
    storageBucket: 'ngwordgame.appspot.com',
    measurementId: 'G-F4M259H2DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZOAxEK81XTramAKZv0HP3aQmReWzJhQg',
    appId: '1:276215361319:android:55f81926902b796f900302',
    messagingSenderId: '276215361319',
    projectId: 'ngwordgame',
    storageBucket: 'ngwordgame.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJhi6kp-webOuazKGZDb3Sd9bjr0s9LeY',
    appId: '1:276215361319:ios:b46662435d559e00900302',
    messagingSenderId: '276215361319',
    projectId: 'ngwordgame',
    storageBucket: 'ngwordgame.appspot.com',
    iosClientId: '276215361319-1vikapnl5r3j2flbd3mq1iv1tn3quo4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngWordGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJhi6kp-webOuazKGZDb3Sd9bjr0s9LeY',
    appId: '1:276215361319:ios:b46662435d559e00900302',
    messagingSenderId: '276215361319',
    projectId: 'ngwordgame',
    storageBucket: 'ngwordgame.appspot.com',
    iosClientId: '276215361319-1vikapnl5r3j2flbd3mq1iv1tn3quo4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngWordGame',
  );

}